import uuid

from fastapi import HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.engagement import GalleryImage
from app.models.enums import GalleryImageType
from app.schemas.engagement import (
    GALLERY_PATH,
    AdminGalleryImage,
    GalleryCreate,
    GalleryImageRead,
    GalleryUpdate,
)


def new_gallery_path(extension: str) -> str:
    # Generated by the server; the client's filename is never used.
    return f"gallery/{uuid.uuid4().hex}.{extension}"


def to_read(image: GalleryImage, url_for) -> GalleryImageRead:
    return GalleryImageRead(
        gallery_image_id=image.gallery_image_id,
        url=url_for(image.storage_path),
        title=image.title,
        description=image.description,
        image_type=image.image_type,
    )


def to_admin(image: GalleryImage, url_for) -> AdminGalleryImage:
    return AdminGalleryImage(
        **to_read(image, url_for).model_dump(),
        is_visible=image.is_visible,
        created_at=image.created_at,
    )


async def list_images(
    session: AsyncSession,
    *,
    visible_only: bool,
    image_type: GalleryImageType | None,
    page: int,
    page_size: int,
) -> tuple[list[GalleryImage], int]:
    where = []
    if visible_only:
        where.append(GalleryImage.is_visible.is_(True))
    if image_type:
        where.append(GalleryImage.image_type == image_type)
    total = await session.scalar(select(func.count()).select_from(GalleryImage).where(*where))
    stmt = (
        select(GalleryImage)
        .where(*where)
        .order_by(GalleryImage.created_at.desc(), GalleryImage.gallery_image_id)
        .offset((page - 1) * page_size)
        .limit(page_size)
    )
    return list((await session.scalars(stmt)).all()), total or 0


async def create_image(session: AsyncSession, data: GalleryCreate) -> GalleryImage:
    if not GALLERY_PATH.match(data.storage_path):
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, "Invalid storage path")
    image = GalleryImage(**data.model_dump())
    session.add(image)
    await session.commit()
    return image


async def _get(session: AsyncSession, image_id: uuid.UUID) -> GalleryImage:
    image = await session.get(GalleryImage, image_id)
    if image is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Gallery image not found")
    return image


async def get_image(session: AsyncSession, image_id: uuid.UUID) -> GalleryImage:
    return await _get(session, image_id)


async def update_image(
    session: AsyncSession, image_id: uuid.UUID, data: GalleryUpdate
) -> GalleryImage:
    image = await _get(session, image_id)
    for field in data.model_fields_set:
        value = getattr(data, field)
        if value is None and field in ("image_type", "is_visible"):
            raise HTTPException(status.HTTP_422_UNPROCESSABLE_CONTENT, f"{field} cannot be null")
        setattr(image, field, value)
    await session.commit()
    return image


async def delete_image(session: AsyncSession, image_id: uuid.UUID) -> str:
    image = await _get(session, image_id)
    path = image.storage_path
    await session.delete(image)
    await session.commit()
    return path
