"""create catalog tables

Revision ID: 8e917b6bdd60
Revises: b3727165445c
Create Date: 2026-10-04 00:10:38.916823
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8e917b6bdd60"
down_revision: str | None = "b3727165445c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_paisa", sa.BigInteger(), nullable=False),
        sa.Column(
            "availability_type",
            sa.Enum("READY_TO_SHIP", "MADE_TO_ORDER", name="product_availability"),
            nullable=False,
        ),
        sa.Column("stock_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_active_units", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("max_active_units >= 0", name="ck_products_capacity_nonneg"),
        sa.CheckConstraint("price_paisa >= 0", name="ck_products_price_nonneg"),
        sa.CheckConstraint("stock_quantity >= 0", name="ck_products_stock_nonneg"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.category_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_index(
        "ix_products_availability_type", "products", ["availability_type"], unique=False
    )
    op.create_index("ix_products_category_id", "products", ["category_id"], unique=False)
    op.create_index("ix_products_is_visible", "products", ["is_visible"], unique=False)
    op.create_table(
        "product_images",
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("image_id"),
    )
    op.create_index("ix_product_images_product_id", "product_images", ["product_id"], unique=False)
    # ### end Alembic commands ###

    # Initial categories (business-rules §4, database.md §6).
    categories = sa.table(
        "categories", sa.column("category_id", sa.Uuid), sa.column("name", sa.Text)
    )
    op.bulk_insert(
        categories,
        [
            {"category_id": uuid.uuid4(), "name": name}
            for name in (
                "Flowers",
                "Amigurumi",
                "House/Home Decor",
                "Key Chains",
                "Accessories",
                "Custom",
            )
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_images_product_id", table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("ix_products_is_visible", table_name="products")
    op.drop_index("ix_products_category_id", table_name="products")
    op.drop_index("ix_products_availability_type", table_name="products")
    op.drop_table("products")
    op.drop_table("categories")
    sa.Enum(name="product_availability").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
