"""create orders payments and business settings

Revision ID: 95574c08ea49
Revises: 47443f29301d
Create Date: 2026-10-04 16:31:18.513357
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "95574c08ea49"
down_revision: str | None = "47443f29301d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EXPIRE_FUNCTION = """
CREATE OR REPLACE FUNCTION expire_unpaid_online_orders() RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    expired integer;
BEGIN
    -- Serialize runs (pg_cron + the API's pre-checkout call) so they cannot deadlock on
    -- product rows.
    PERFORM pg_advisory_xact_lock(hashtext('expire_unpaid_online_orders'));

    WITH due AS (
        SELECT o.order_id
        FROM orders o
        WHERE o.status = 'PENDING'
          AND o.payment_deadline_at IS NOT NULL
          AND o.payment_deadline_at <= now()
          -- unpaid online order: it has an ONLINE payment and nothing beyond PENDING
          AND EXISTS (SELECT 1 FROM payments p
                      WHERE p.order_id = o.order_id AND p.method = 'ONLINE')
          AND NOT EXISTS (SELECT 1 FROM payments p
                          WHERE p.order_id = o.order_id AND p.status <> 'PENDING')
        FOR UPDATE OF o SKIP LOCKED
    ), cancelled AS (
        UPDATE orders o
        SET status = 'CANCELLED', cancelled_at = now(), updated_at = now()
        FROM due
        WHERE o.order_id = due.order_id
        RETURNING o.order_id
    ), release AS (
        -- Ready-to-ship stock goes back. Made-to-order capacity is derived from active
        -- orders, so cancelling the order releases it automatically.
        SELECT oi.product_id, sum(oi.quantity)::integer AS qty
        FROM order_items oi
        JOIN cancelled c ON c.order_id = oi.order_id
        JOIN products pr ON pr.product_id = oi.product_id
        WHERE pr.availability_type = 'READY_TO_SHIP'
        GROUP BY oi.product_id
    ), restocked AS (
        UPDATE products pr
        SET stock_quantity = pr.stock_quantity + r.qty, updated_at = now()
        FROM release r
        WHERE pr.product_id = r.product_id
        RETURNING pr.product_id
    )
    SELECT count(*) INTO expired FROM cancelled;

    RETURN expired;
END
$$;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_settings",
        sa.Column("setting_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("whatsapp", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("delivery_information", sa.Text(), nullable=True),
        sa.Column("delivery_fee_paisa", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("delivery_fee_paisa >= 0", name="ck_business_settings_fee_nonneg"),
        sa.PrimaryKeyConstraint("setting_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("customer_name", sa.Text(), nullable=False),
        sa.Column("customer_email", sa.Text(), nullable=False),
        sa.Column("customer_phone", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("delivery_name", sa.Text(), nullable=False),
        sa.Column("delivery_house_no", sa.Text(), nullable=False),
        sa.Column("delivery_street_number", sa.Text(), nullable=True),
        sa.Column("delivery_city", sa.Text(), nullable=False),
        sa.Column("delivery_province", sa.Text(), nullable=True),
        sa.Column("delivery_postal_code", sa.Text(), nullable=False),
        sa.Column("delivery_country", sa.Text(), nullable=False),
        sa.Column("subtotal_paisa", sa.BigInteger(), nullable=False),
        sa.Column("delivery_fee_paisa", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("payment_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_charge_paisa", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("charge_waived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cancellation_charge_paisa >= 0", name="ck_orders_charge_nonneg"),
        sa.CheckConstraint("delivery_fee_paisa >= 0", name="ck_orders_delivery_fee_nonneg"),
        sa.CheckConstraint("subtotal_paisa >= 0", name="ck_orders_subtotal_nonneg"),
        sa.CheckConstraint(
            "total_amount_paisa = subtotal_paisa + delivery_fee_paisa", name="ck_orders_total_sum"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"], unique=False)
    op.create_index(
        "ix_orders_payment_deadline_at", "orders", ["payment_deadline_at"], unique=False
    )
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("product_name_snapshot", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_at_purchase_paisa", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
        sa.CheckConstraint("unit_price_at_purchase_paisa >= 0", name="ck_order_items_price_nonneg"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.order_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("order_item_id"),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)
    op.create_index("ix_order_items_product_id", "order_items", ["product_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.Enum("COD", "ONLINE", name="payment_method"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "PARTIALLY_REFUNDED", "REFUNDED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("amount_paisa", sa.BigInteger(), nullable=False),
        sa.Column("refunded_amount_paisa", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("provider_reference", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_paisa >= 0", name="ck_payments_amount_nonneg"),
        sa.CheckConstraint("refunded_amount_paisa <= amount_paisa", name="ck_payments_refund_cap"),
        sa.CheckConstraint("refunded_amount_paisa >= 0", name="ck_payments_refunded_nonneg"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.order_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.UniqueConstraint("provider_reference"),
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"], unique=False)
    # ### end Alembic commands ###

    # The single business-settings record (database.md §18). Delivery fee: Rs 200, changeable
    # until the admin UI exists with:  UPDATE business_settings SET delivery_fee_paisa = ...
    settings = sa.table(
        "business_settings",
        sa.column("setting_id", sa.Uuid),
        sa.column("business_name", sa.Text),
        sa.column("delivery_fee_paisa", sa.BigInteger),
    )
    op.bulk_insert(
        settings,
        [
            {
                "setting_id": uuid.uuid4(),
                "business_name": "Crochet Shop",
                "delivery_fee_paisa": 20000,
            }
        ],
    )
    op.execute(EXPIRE_FUNCTION)


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS expire_unpaid_online_orders()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_order_id", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_order_items_product_id", table_name="order_items")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_payment_deadline_at", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_table("orders")
    op.drop_table("business_settings")
    # ### end Alembic commands ###
    for enum_name in ("payment_status", "payment_method", "order_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
