"""create addresses and wishlist

Revision ID: 47443f29301d
Revises: 8e917b6bdd60
Create Date: 2026-10-04 13:50:28.568792
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47443f29301d"
down_revision: str | None = "8e917b6bdd60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("address_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("house_no", sa.Text(), nullable=False),
        sa.Column("street_number", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("province", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("address_id"),
    )
    op.create_index("ix_addresses_customer_id", "addresses", ["customer_id"], unique=False)
    op.create_table(
        "wishlist_items",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("customer_id", "product_id"),
    )
    op.create_index("ix_wishlist_items_product_id", "wishlist_items", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wishlist_items_product_id", table_name="wishlist_items")
    op.drop_table("wishlist_items")
    op.drop_index("ix_addresses_customer_id", table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
