"""create engagement tables

Revision ID: 5ec46e026108
Revises: 28d59f02e684
Create Date: 2026-10-04 22:50:15.722429
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5ec46e026108"
down_revision: str | None = "28d59f02e684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gallery_images",
        sa.Column("gallery_image_id", sa.Uuid(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "image_type",
            sa.Enum(
                "SHOP",
                "DESIGN",
                "BEHIND_THE_SCENES",
                "CUSTOMER_PHOTO",
                "OTHER",
                name="gallery_image_type",
            ),
            nullable=False,
        ),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("gallery_image_id"),
    )
    op.create_index(
        "ix_gallery_images_visible_type",
        "gallery_images",
        ["is_visible", "image_type"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("whatsapp_number", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "READ", "REPLIED", "ARCHIVED", name="message_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index("ix_messages_status", "messages", ["status"], unique=False)
    op.create_table(
        "custom_orders",
        sa.Column("custom_order_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("whatsapp_number", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("budget_paisa", sa.BigInteger(), nullable=True),
        sa.Column("required_date", sa.Date(), nullable=True),
        sa.Column("reference_image_path", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "IN_DISCUSSION",
                "ACCEPTED",
                "IN_PROGRESS",
                "COMPLETED",
                "DECLINED",
                "CANCELLED",
                name="custom_order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "budget_paisa IS NULL OR budget_paisa >= 0", name="ck_custom_orders_budget"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("custom_order_id"),
    )
    op.create_index("ix_custom_orders_created_at", "custom_orders", ["created_at"], unique=False)
    op.create_index("ix_custom_orders_customer_id", "custom_orders", ["customer_id"], unique=False)
    op.create_index("ix_custom_orders_status", "custom_orders", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ORDER_PLACED",
                "ORDER_CONFIRMED",
                "ORDER_STATUS_CHANGED",
                "ORDER_SHIPPED",
                "ORDER_DELIVERED",
                "PAYMENT_SUCCESS",
                "PAYMENT_FAILURE",
                "NEW_PRODUCT",
                "CUSTOM_ORDER_UPDATE",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UNREAD", "READ", name="notification_status"),
            server_default="UNREAD",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_index(
        "ix_notifications_customer_status",
        "notifications",
        ["customer_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_name_snapshot", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_reviews_rating_range"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.customer_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.order_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.product_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("review_id"),
        sa.UniqueConstraint("customer_id", "product_id", name="uq_reviews_customer_product"),
    )
    op.create_index("ix_reviews_order_id", "reviews", ["order_id"], unique=False)
    op.create_index("ix_reviews_product_id", "reviews", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_product_id", table_name="reviews")
    op.drop_index("ix_reviews_order_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_notifications_customer_status", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_custom_orders_status", table_name="custom_orders")
    op.drop_index("ix_custom_orders_customer_id", table_name="custom_orders")
    op.drop_index("ix_custom_orders_created_at", table_name="custom_orders")
    op.drop_table("custom_orders")
    op.drop_index("ix_messages_status", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_gallery_images_visible_type", table_name="gallery_images")
    op.drop_table("gallery_images")
    # ### end Alembic commands ###
    for enum_name in (
        "notification_status",
        "notification_type",
        "custom_order_status",
        "message_status",
        "gallery_image_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
